version: 2
jobs:
  build:
   docker: 
     - image: circleci/ruby:2.4.1-jessie
   steps:
    - checkout
    - run: 
       name: First Steps
       command: | 
         echo 'Hello World'
         echo 'A delivery pipeline'
    - run:
       name: Code has Arrived
       command: | 
          ls -al
          echo '^^^^That should looks familiar^^^'
