version: 2
jobs:
 build:
   #machine: true
   docker:
     - image: circleci/ruby:2.4.1-jessie
   #working_directory: ""
   envrionment: 
    TEST_CLUSTER_PORT: '9250'
    TEST_CLUSTER_NETWORK_HOST: localhost
    TEST_CLUSTER_COMMAND: 'elasticsearch-5.4.0/bin/elasticsearch'
    PLATFORM_AUTHORIZE_URL: "Testing URL"
  steps: 
    - name: "Testing"
    - run: pwd
