version: 2
jobs:
 build:
   #machine: true
   #working_directory: ""
   docker:
     - image: circleci/openjdk:8u131-jdk
     - image: circleci/ruby:2.4.1-jessie
       environment:
         TEST_CLUSTER_PORT: 9250
         TEST_CLUSTER_NETWORK_HOST: localhost
         TEST_CLUSTER_COMMAND: elasticsearch-5.4.0/bin/elasticsearch
         PLATFORM_AUTHORIZE_URL: Testing_URL
   steps: 
    - checkout
    - run: ls
    - run: java --version
    - run: javac --version
    - run: cat ~/.bashrc
    #- run: sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0/bin/java
    #- run: sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
    #- run: echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ~/.circlerc
    - run: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.tar.gz
    - run: tar -xvf elasticsearch-5.4.0.tar.gz
    - run: ls -l
    - save_cache:
        key: dependency-cache
        paths:
          - elasticsearch-5.4.0
