version: 2
jobs:
 build:
   #machine: true
   docker:
     - image: circleci/ruby:2.4.1-jessie
   #working_directory: ""
   steps: 
    - run: echo 'export TEST_CLUSTER_PORT=9250' >> $BASH_ENV
    - run: echo 'export TEST_CLUSTER_NETWORK_HOST=localhost' >> $BASH_ENV
    - run: echo 'export TEST_CLUSTER_COMMAND=elasticsearch-5.4.0/bin/elasticsearch' >> $BASH_ENV
    - run: echo 'export PLATFORM_AUTHORIZE_URL=Testing_URL' >> $BASH_ENV
    - run: pwd
