version: 2
jobs:
  build:
   docker: 
     - image: circleci/ruby:2.4.1-jessie
   steps:
    - run: 
       name: "First Steps"
       command: | 
         echo 'Hello World'
         echo 'A delivery pipeline'
